import React, { useEffect, useState } from 'react';
import { ArrowRight, Check, Eye, EyeOff, LockKeyhole, Mail, ShieldCheck } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext.jsx';
import toast from 'react-hot-toast';
import './AuthPages.css';
import { isValidEmail } from '../utils/validation.js';

function BrandPanel() {
  return <aside className="auth-brand-panel" aria-label="Medithrex overview"><div className="auth-brand-orb auth-brand-orb--one" /><div className="auth-brand-orb auth-brand-orb--two" /><div className="auth-brand-inner"><Link to="/" className="auth-brand-logo"><span className="auth-logo-mark">M</span><span>medithrex</span></Link><div className="auth-brand-copy"><span className="auth-kicker">Healthcare, connected</span><h2>Better equipment.<br /><em>Better outcomes.</em></h2><p>One trusted workspace for sourcing, quoting, and managing the medical equipment your team relies on.</p></div><div className="auth-proof-card"><div className="auth-proof-icon"><ShieldCheck size={18} /></div><div><strong>Built for clinical teams</strong><span>Secure access to your organisation’s workspace</span></div><Check size={17} className="auth-proof-check" /></div></div><div className="auth-brand-footer"><span>MEDICAL EQUIPMENT SOLUTIONS</span><span>EST. 2024</span></div></aside>;
}

export default function LoginPage() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false);
  const { login, user } = useAuth(); const navigate = useNavigate();
  useEffect(() => { if (user) navigate(user.role === 'admin' ? '/admin' : '/account', { replace: true }); }, [user, navigate]);
  const handleSubmit = async (e) => { e.preventDefault(); if (!email || !password) return toast.error('Please fill in all fields'); if (!isValidEmail(email)) return toast.error('Please enter a valid email address'); setLoading(true); try { const u = await login(email.trim().toLowerCase(), password); toast.success(`Welcome back, ${u.name}`); navigate(u.role === 'admin' ? '/admin' : '/account', { replace: true }); } catch (err) { toast.error(err.response?.data?.error || 'Invalid email or password'); } finally { setLoading(false); } };
  return <div className="auth-page"><BrandPanel /><main className="auth-form-panel"><div className="auth-mobile-logo"><Link to="/" className="auth-brand-logo"><span className="auth-logo-mark">M</span><span>medithrex</span></Link></div><div className="auth-form-wrap"><div className="auth-form-header"><span className="auth-step">01 <span>/</span> ACCOUNT ACCESS</span><h1>Welcome back</h1><p>Sign in to continue to your Medithrex workspace.</p></div><form onSubmit={handleSubmit} className="auth-form" noValidate><label className="auth-field"><span>Email address</span><div className="auth-input-wrap"><Mail size={18} /><input type="email" placeholder="name@organisation.com" value={email} onChange={(e) => setEmail(e.target.value)} autoComplete="email" /></div></label><label className="auth-field"><span>Password</span><div className="auth-input-wrap"><LockKeyhole size={18} /><input type={showPassword ? 'text' : 'password'} placeholder="Enter your password" value={password} onChange={(e) => setPassword(e.target.value)} autoComplete="current-password" /><button type="button" className="auth-password-toggle" onClick={() => setShowPassword((s) => !s)} aria-label={showPassword ? 'Hide password' : 'Show password'}>{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></label><div className="auth-form-meta"><label className="auth-check-label"><input type="checkbox" /> <span>Keep me signed in</span></label><Link to="/forgot-password" className="auth-link">Forgot password?</Link></div><button type="submit" className="auth-submit-btn" disabled={loading}>{loading ? 'Signing in…' : <>Sign in to workspace <ArrowRight size={18} /></>}</button></form><div className="auth-switch"><span>New to Medithrex?</span><Link to="/register">Create an account <ArrowRight size={15} /></Link></div><p className="auth-legal">By continuing, you agree to our <Link to="/terms-of-service">Terms of Service</Link> and <Link to="/privacy-policy">Privacy Policy</Link>.</p></div></main></div>;
}
