import React, { useEffect, useState } from 'react';
import { ArrowRight, Check, Eye, EyeOff, LockKeyhole, Mail, Phone, UserRound } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext.jsx';
import toast from 'react-hot-toast';
import './AuthPages.css';
import { isStrongPassword, isValidEmail, isValidKenyanPhone, KENYAN_PHONE_HINT, normalizeKenyanPhone, PASSWORD_HINT } from '../utils/validation.js';

function RegisterBrandPanel() { return <aside className="auth-brand-panel auth-brand-panel--register"><div className="auth-brand-orb auth-brand-orb--one" /><div className="auth-brand-orb auth-brand-orb--two" /><div className="auth-brand-inner"><Link to="/" className="auth-brand-logo"><span className="auth-logo-mark">M</span><span>medithrex</span></Link><div className="auth-brand-copy"><span className="auth-kicker">Your team’s advantage</span><h2>Everything you need<br /><em>to move forward.</em></h2><p>Create a workspace that makes medical procurement clearer, faster, and more accountable.</p></div><div className="auth-feature-list"><div><span>01</span><p><strong>Source with confidence</strong><small>Quality equipment from a trusted partner.</small></p></div><div><span>02</span><p><strong>Keep teams aligned</strong><small>Quotes, orders, and updates in one place.</small></p></div><div><span>03</span><p><strong>Stay in control</strong><small>Visibility from request to delivery.</small></p></div></div></div><div className="auth-brand-footer"><span>MEDICAL EQUIPMENT SOLUTIONS</span><span>EST. 2024</span></div></aside>; }
const Field = ({ icon: Icon, label, type = 'text', value, onChange, placeholder, autoComplete, children }) => <label className="auth-field"><span>{label}</span><div className="auth-input-wrap"><Icon size={18} /><input type={type} placeholder={placeholder} value={value} onChange={onChange} autoComplete={autoComplete} />{children}</div></label>;

export default function RegisterPage() {
  const [form, setForm] = useState({ name: '', email: '', phone: '', password: '', confirmPassword: '' }); const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false); const { register, user } = useAuth(); const navigate = useNavigate();
  useEffect(() => { if (user) navigate(user.role === 'admin' ? '/admin' : '/account', { replace: true }); }, [user, navigate]);
  const update = (field) => (e) => setForm((prev) => ({ ...prev, [field]: e.target.value }));
  const passwordsMatch = form.confirmPassword.length > 0 && form.password === form.confirmPassword;
  const handleSubmit = async (e) => { e.preventDefault(); const { name, email, phone, password, confirmPassword } = form; if (!name || !email || !phone || !password || !confirmPassword) return toast.error('Please fill in all required fields'); if (!isValidEmail(email)) return toast.error('Please enter a valid email address'); if (!isValidKenyanPhone(phone)) return toast.error(KENYAN_PHONE_HINT); if (!isStrongPassword(password)) return toast.error(PASSWORD_HINT); if (password !== confirmPassword) return toast.error('Passwords do not match'); setLoading(true); try { const u = await register({ name, email: email.trim().toLowerCase(), phone: normalizeKenyanPhone(phone), password }); toast.success('Account created'); navigate(u.role === 'admin' ? '/admin' : '/account', { replace: true }); } catch (err) { toast.error(err.response?.data?.error || 'Registration failed'); } finally { setLoading(false); } };
  return <div className="auth-page"><RegisterBrandPanel /><main className="auth-form-panel"><div className="auth-mobile-logo"><Link to="/" className="auth-brand-logo"><span className="auth-logo-mark">M</span><span>medithrex</span></Link></div><div className="auth-form-wrap auth-form-wrap--register"><div className="auth-form-header"><span className="auth-step">01 <span>/</span> GET STARTED</span><h1>Create your workspace</h1><p>Join the teams making healthcare procurement simpler.</p></div><form onSubmit={handleSubmit} className="auth-form" noValidate><div className="auth-field-grid"><Field icon={UserRound} label="Full name" value={form.name} onChange={update('name')} placeholder="Jane Mwangi" autoComplete="name" /><Field icon={Phone} label="Kenyan phone number" type="tel" value={form.phone} onChange={update('phone')} placeholder="0790 080 903" autoComplete="tel" /></div><Field icon={Mail} label="Email address" type="email" value={form.email} onChange={update('email')} placeholder="name@organisation.com" autoComplete="email" /><div className="auth-field-grid"><div><Field icon={LockKeyhole} label="Create password" type={showPassword ? 'text' : 'password'} value={form.password} onChange={update('password')} placeholder="At least 8 characters" autoComplete="new-password"><button type="button" className="auth-password-toggle" onClick={() => setShowPassword((s) => !s)} aria-label={showPassword ? 'Hide password' : 'Show password'}>{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></Field><p className={`auth-validation-note ${form.password && isStrongPassword(form.password) ? 'is-valid' : ''}`}>{form.password && isStrongPassword(form.password) ? 'Strong password' : PASSWORD_HINT}</p></div><div><Field icon={LockKeyhole} label="Confirm password" type={showPassword ? 'text' : 'password'} value={form.confirmPassword} onChange={update('confirmPassword')} placeholder="Repeat password" autoComplete="new-password" /><p className={`auth-validation-note ${passwordsMatch ? 'is-valid' : form.confirmPassword ? 'is-invalid' : ''}`}>{passwordsMatch ? 'Passwords match' : form.confirmPassword ? 'Passwords do not match' : 'Re-enter your password'}</p></div></div><label className="auth-check-label auth-terms-check"><input type="checkbox" required /> <span>I agree to the <Link to="/terms-of-service">Terms of Service</Link> and <Link to="/privacy-policy">Privacy Policy</Link>.</span></label><button type="submit" className="auth-submit-btn" disabled={loading}>{loading ? 'Creating workspace…' : <>Create workspace <ArrowRight size={18} /></>}</button></form><div className="auth-switch"><span>Already have an account?</span><Link to="/login">Sign in <ArrowRight size={15} /></Link></div><div className="auth-security-note"><Check size={15} /> Your information is encrypted and kept private.</div></div></main></div>;
}
